#!/bin/bash

# Update packages
echo "Updating distribution packages..."
sudo apt update && sudo apt upgrade -y

echo " ____  _____  ___  _  _  ____  ____  ____  ____     ____  ____  _____  ____"
echo "(  _ \(  _  )/ __)( )/ )( ___)(  _ \( ___)(  _ \   (_  _)(_  _)(  _  )(  _ \\"
echo " )(_) ))(_)(( (__  )  (  )__)  )   / )__)  )(_) )   _)(_   )(   )(_)(  )___/"
echo "(____/(_____)\___)(_)\_)(____)(_)\_)(____)(____/   (____) (__) (_____)(__)"

echo ""

echo "Installing host development environment..."

echo ""

# Copy ssh keys
read -e -p "Enter the path of your public SSH key:\n(/mnt/c/users/moi/.ssh/publickey.pub)" FILEPATH
read -e -p "Enter the ssh username: " NAME
mkdir -p /home/$NAME/.ssh -m 777
cp $FILEPATH /home/$NAME/.ssh/authorized_keys
chown -R $NAME:$NAME /home/$NAME/.ssh
cp $FILEPATH /root/.ssh/authorized_keys

# ssh port
read -e -p "Enter the SSH port: " PORT
mkdir -p /etc/ssh/sshd_config.d -m 777
echo "port $PORT" >> /etc/ssh/sshd_config.d/docker.conf

# Install PHP, Open SSH Server and Git
echo "Installing PHP, Open SSH Server et Git..."
sudo apt install -y php-cli php-mbstring php-xml php-curl unzip curl openssh-server git

# Install Composer
echo "Installing Composer..."
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
composer --version

echo "Development environment ready."