#!/bin/bash

if [[ $1 == install ]]; then
  echo Installing iTop $2
  git clone https://github.com/bdalsass/sample.git
  cd sample
  git config --global --add safe.directory $(pwd)
  git fetch --all
  git switch -c $2 origin/$2

  mkdir log
  chown 'www-data:root' log
  chown 'www-data:root' data
  chown 'www-data:root' conf
else
  echo "Uninstalling iTop"
fi